name: publish Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Remove existing code
        run: make clean

      - name: Generate code from *.proto
        run: make generate

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Vikram Venkataramanan
          author_email: vikram.venkataramanan@mail.utoronto.ca
          message: "generate proto files"
          add: "lib/proto/*"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Vikram Venkataramanan
          author_email: vikram.venkataramanan@mail.utoronto.ca
          message: "generate node files"
          add: "lib/node/*"

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@viktree"
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: cd lib/node && yarn version --minor
      - run: git pull
      #- run: git push --tags
      - run: git push
      - run: cd lib/node && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GHUB_TOKEN}}
